[package]
name = "s7-1500-software-controller-loader"
version = "0.1.0"
authors = ["Tom Dohrmann <t.dohrmann@enlyze.com>"]
edition = "2021"

[dependencies]
log = { version = "0.4.17", default-features = false }
uart_16550 = "0.2.18"
uefi = "0.19.0"
xmas-elf = "0.9.0"
x86_64 = "0.14.10"
